# Generated by Django 5.1.7 on 2025-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='icon',
        ),
    ]
