# Generated by Django 5.1.7 on 2025-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
