# Generated by Django 5.1.7 on 2025-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(max_length=18),
        ),
    ]
