# Generated by Django 5.1.7 on 2025-08-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='observations',
            new_name='observation',
        ),
    ]
