# Generated by Django 5.1.7 on 2025-09-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_discipline_icon'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disciplines.discipline'),
            preserve_default=False,
        ),
    ]
