# Generated by Django 5.1.7 on 2025-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('treatments', '0002_treatment_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='rooms',
            field=models.ManyToManyField(related_name='treatments', to='places.place'),
        ),
    ]
