# Generated by Django 5.1.7 on 2025-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isWorker',
            field=models.BooleanField(default=False),
        ),
    ]
