# Generated by Django 5.1.7 on 2025-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
