# Generated by Django 5.1.7 on 2025-09-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_isworker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isWorker',
            new_name='is_worker',
        ),
    ]
