# Generated by Django 5.1.7 on 2025-09-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
