# Generated by Django 5.1.7 on 2025-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='indexedCell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
