# Generated by Django 5.1.7 on 2025-09-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('workers', '0003_alter_worker_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
    ]
