# Generated by Django 5.1.7 on 2025-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('canceled', 'Canceled')], default='unscheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sus',
            field=models.BooleanField(default=False, verbose_name='SUS Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
