# Generated by Django 5.1.7 on 2025-03-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_indexedcell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='indexedCell',
        ),
    ]
