# Generated by Django 5.1.7 on 2025-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
