# Generated by Django 5.1.7 on 2025-05-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_indexedcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='appointments.room'),
            preserve_default=False,
        ),
    ]
