# Generated by Django 5.1.7 on 2025-09-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_priority_appointment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='note',
            new_name='observation',
        ),
    ]
