# Generated by Django 5.1.7 on 2025-05-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_room_appointment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='identifier',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
