# Generated by Django 5.1.7 on 2025-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_note_appointment_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Não Agendado'), ('scheduled', 'Agendado'), ('completed', 'Concluído'), ('missed', 'Não Compareceu'), ('canceled', 'Cancelado')], default='unscheduled', max_length=20),
        ),
    ]
