# Generated by Django 5.1.7 on 2025-09-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Não Agendado'), ('scheduled', 'Agendado'), ('completed', 'Concluído'), ('missed', 'Não Compareceu'), ('canceled', 'Cancelado'), ('reservation', 'Reserva')], default='unscheduled', max_length=20),
        ),
    ]
