# Generated by Django 5.1.7 on 2025-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_room_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='identifier',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
