# Generated by Django 5.1.7 on 2025-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Não Agendado'), ('scheduled', 'Agendado'), ('unconfirmed', 'A Confirmar'), ('completed', 'Concluído'), ('missed', 'Não Compareceu'), ('canceled', 'Cancelado'), ('reservation', 'Reserva'), ('solicitation', 'Solicitação')], default='unscheduled', max_length=20),
        ),
    ]
