# Generated by Django 5.1.7 on 2025-05-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_room_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='identifier',
            new_name='name',
        ),
    ]
