# Generated by Django 5.1.7 on 2025-09-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
