# Generated by Django 5.1.7 on 2025-09-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
    ]
