# Generated by Django 5.1.7 on 2025-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
